exports.default = [
  'peanut butter casein protein powder',
  'scoop chocolate oat protein powder',
  'vanilla plant-based protein powder',
  'peanut butter plant-based protein',
  'fat free vanilla frozen yogurt',
  'fat-free vanilla frozen yogurt',
  'low fat vanilla frozen yogurt',
  'chocolate whey protein powder',
  'vanilla rice protein powder',
  'vanilla whey protein powder',
  'plant based protein powder',
  'unsweetened cocoa powder',
  'unsweetened almond milk',
  'frozen pineapple chunks',
  'chocolate whey protein',
  'blue spirulina powder',
  'chopped medium peach',
  'frozen banana chunks',
  'frozen mixed berries',
  'vanilla whey protein',
  'light coconut cream',
  'frozen strawberries',
  'rice protein powder',
  'vanilla whey powder',
  'frozen blueberries',
  'frozen raspberries',
  'pea protein powder',
  'light coconut milk',
  'organic pineapple',
  'lemon balm leaves',
  'lemon balm leaves',
  'frozen pineapple',
  'ground cinnamon',
  'pineapple juice',
  'pineapple juice',
  'cranberry juice',
  'cucumber slices',
  'vanilla extract',
  'ground flaxseed',
  'chopped almonds',
  'cuporange juice',
  'touch of honey',
  'fresh lemonade',
  'coconut yogurt',
  'chopped pecans',
  'coconut flakes',
  'ground coffee',
  'coconut water',
  'frozen banana',
  'peanut butter',
  'coconut cream',
  'passion fruit',
  'almond butter',
  'cashew butter',
  'blackberries',
  'strawberries',
  'orange juice',
  'greek yogurt',
  'sweet potato',
  'cocoa powder',
  'medjool date',
  'fresh ginger',
  'pitted dates',
  'coconut milk',
  'whey protein',
  'frozen mango',
  'rolled oats',
  'blueberries',
  'oat squares',
  'apple cider',
  'apple juice',
  'raspberries',
  'green apple',
  'maple syrup',
  'lemon juice',
  'orange zest',
  'coconut oil',
  'date-pitted',
  'peeled-beet',
  'chia seeds',
  'watermelon',
  'flaxs seed',
  'cocoa nibs',
  'quick oats',
  'lime juice',
  'skim milk',
  'ice cubes',
  'pineapple',
  'sprinkles',
  'soy milk',
  'chai tea',
  'lemonade',
  'bok choy',
  'oat milk',
  'beetroot',
  'cinnamon',
  'sea salt',
  'espresso',
  'turmeric',
  'almonds',
  'spinach',
  'coconut',
  'granola',
  'walnuts',
  'avocado',
  'pecans',
  'banana',
  'carrot',
  'papaya',
  'orange',
  'ginger',
  'mango',
  'honey',
  'peach',
  'water',
  'kiwi',
  'kale',
  'salt',
  'lime',
  'ice'
];