exports.default = [
  'fat free vanilla frozen yogurt',
  'low fat vanilla frozen yogurt',
  'organic pineapple',
  'ground cinnamon',
  'pineapple juice',
  'cranberry juice',
  'pineapple juice',
  'ground coffee',
  'coconut water',
  'coconut cream',
  'touch of honey',
  'fresh lemonade',
  'peanut butter',
  'strawberries',
  'orange juice',
  'apple juice',
  'rolled oats',
  'apple cider',
  'oat squares',
  'ice cubes',
  'skim milk',
  'chai tea',
  'pineapple',
  'coconut',
  'almonds',
  'pecans',
  'kale',
  'spinach',
  'mango',
  'kiwi',
  'soy milk',
  'granola',
  'banana',
  'peach',
  'honey',
  'lemonade',
  'raspberries',
  'blueberries',
  'blackberries'
];