exports.default = [
  'peanut butter casein protein powder',
  'scoop chocolate oat protein powder',
  'vanilla plant-based protein powder',
  'plant-based vanilla protein powder',
  'peanut butter plant-based protein',
  'fat free vanilla frozen yogurt',
  'fat-free vanilla frozen yogurt',
  'low fat vanilla frozen yogurt',
  'chocolate whey protein powder',
  'chocolate rice protein powder',
  'vanilla whey protein powder',
  'vanilla rice protein powder',
  'plant based protein powder',
  'plant-based protein powder',
  'unsweetened cocoa powder',
  'unsweetened almond milk',
  'frozen pineapple chunks',
  'low-fat vanilla yogurt',
  'chocolate whey protein',
  'blue spirulina powder',
  'casein protein powder',
  'chocolate whey powder',
  'chopped medium peach',
  'frozen banana chunks',
  'frozen mixed berries',
  'vanilla whey protein',
  'light coconut cream',
  'frozen strawberries',
  'vanilla whey powder',
  'rice protein powder',
  'vanilla almond milk',
  'frozen blackberries',
  'frozen blueberries',
  'frozen raspberries',
  'pea protein powder',
  'light coconut milk',
  'oat protein powder',
  'organic pineapple',
  'lemon balm leaves',
  'lemon balm leaves',
  'frozen pineapple',
  'pineapple juice',
  'cranberry juice',
  'ground cinnamon',
  'pineapple juice',
  'cucumber slices',
  'vanilla extract',
  'ground flaxseed',
  'cuporange juice',
  'chopped almonds',
  'touch of honey',
  'fresh lemonade',
  'coconut yogurt',
  'coconut flakes',
  'chopped pecans',
  'coconut water',
  'frozen banana',
  'peanut butter',
  'coconut cream',
  'ground coffee',
  'passion fruit',
  'almond butter',
  'cashew butter',
  'blackberries',
  'strawberries',
  'greek yogurt',
  'orange juice',
  'sweet potato',
  'cocoa powder',
  'whey protein',
  'medjool date',
  'fresh ginger',
  'coconut milk',
  'frozen mango',
  'pitted dates',
  'rolled oats',
  'apple cider',
  'blueberries',
  'oat squares',
  'raspberries',
  'green apple',
  'maple syrup',
  'lemon juice',
  'apple juice',
  'orange zest',
  'date-pitted',
  'almond milk',
  'coconut oil',
  'watermelon',
  'chia seeds',
  'flaxs seed',
  'cocoa nibs',
  'quick oats',
  'lime juice',
  'skim milk',
  'ice cubes',
  'pineapple',
  'sprinkles',
  'chai tea',
  'soy milk',
  'chai tea',
  'soy milk',
  'lemonade',
  'bok choy',
  'oat milk',
  'beetroot',
  'cinnamon',
  'sea salt',
  'turmeric',
  'espresso',
  'coconut',
  'spinach',
  'almonds',
  'granola',
  'walnuts',
  'avocado',
  'pecans',
  'banana',
  'papaya',
  'carrot',
  'orange',
  'ginger',
  'celery',
  'matcha',
  'mango',
  'honey',
  'peach',
  'water',
  'apple',
  'kiwi',
  'kale',
  'salt',
  'beet',
  'lime',
  'date',
  'ice'
];